from turtle import *
size = int(input('Введите желаемый размер'))
v = int(input('в ведите желаемый размер поворота в верх или в низ'))
v1 = int(input('введите жилаемый размер влева право'))
v3 = int(input('введите сколько раз повторять'))
for i in range(v3):
    fd(size)
    lt(v)
    fd(size)
    rt(v1)
    fd(size)
    lt(v)
    fd(size)
    rt(v1)
    fd(size)
    rt(v1)
    fd(size)
    lt(v)
    fd(size)
    rt(v1)
    fd(size)
    lt(v)
    fd(size)
    
